language: elm

elm:
  - latest-0.19.1

elm_test: 0.19.1

elm_format: 0.8.2

before_deploy:
  - elm make src/Main.elm --output=dist/app.js --optimize

deploy:
  skip_cleanup: true
  local-dir: dist/
  provider: pages
  keep-history: true
  fqdn: plata.m.ie.mk
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
